--! DELETE THISE LINES LATER
drop schema if exists gamecollector CASCADE;
create schema gamecollector;
-- FOR EASE OF USE WHILE IN DEV --!

-- set search_path to gamecollector;

create table t_country (
	countryCode	varchar(2) primary key not null,
	countryName	varchar(80) not null);
	
-- alter table t_country set owner to postgres;
	
create table t_company (
	pk_companyID serial primary key,
	companyName varchar(50) not null);

create table t_console(
	pk_consoleID serial primary key,
	releaseDate date not null);

create table t_game (
	pk_gameID	serial primary key,
	name	varchar(255) not null);		
	
create table t_review (
	pk_reviewID serial primary key,
	reviewTitle varchar(100) not null,
	reviewBody text not null,
	reviewScore real check (reviewScore > 0) check (reviewScore < 10.1));	

create table t_user(
	pk_userID serial primary key,
	username varchar(45) not null,
	emailAddress varchar(255) not null,
	displayName varchar(45) not null,
	firstName varchar(45),
	lastName varchar(45),
	-- I wouldn't expect the service to pass this, so default it.
	creationDate timestamp with time zone default now(),
	activeYN varchar(1) default 'N',
	lastLogin timestamp with time zone);	

-- Establish relationships between tables. Doing this hear to avoid headaches with tables not exiting prior to creation.

alter table t_review
	-- could in the future change this to a 'person'? this could allow for external reviews. Right now we're saying that every review comes from a user of the system.
	add column user_reviewerID integer references t_user(pk_userID) not null;

alter table t_user	
	add column country_registeredCountry varchar(2) references t_country(countryCode);

alter table t_game
	add column console_consoleID integer references t_console(pk_consoleID) not null,
	add column company_publisherID integer references t_company(pk_companyID) not null,
	add column company_developerID integer references t_company(pk_companyID) not null;

alter table t_company
	add column country_countryID varchar(2) references t_country(countryCode) not null;

INSERT INTO t_country values
	('ad','Andorra'),
	('af','Afghanistan'),
	('ag','Antigua and Barbuda'),
	('ai','Anguilla'),
	('al','Albania'),
	('am','Armenia'),
	('ao','Angola'),
	('aq','Antarctica'),
	('ar','Argentina'),
	('as','American Samoa'),
	('au','Australia'),
	('aw','Aruba'),
	('ax','Aland Islands'),
	('az','Azerbaijan'),
	('at','Austria'),
	('dz','Algeria'),
	('bs','Bahamas'),
	('bh','Bahrain'),
	('bd','Bangladesh'),
	('bb','Barbados'),
	('by','Belarus'),
	('be','Belgium'),
	('bz','Belize'),
	('bj','Benin'),
	('bm','Bermuda'),
	('bt','Bhutan'),
	('bo','Plurinational State of Bolivia'),
	('bq','Sint Eustatius and Saba Bonaire'),
	('ba','Bosnia and Herzegowina'),
	('bw','Botswana'),
	('bv','Bouvet Island'),
	('br','Brazil'),
	('io','British Indian Ocean Territory'),
	('bn','Brunei Darussalam'),
	('bg','Bulgaria'),
	('bf','Burkina Faso'),
	('bi','Burundi'),
	('kh','Cambodia'),
	('cm','Cameroon'),
	('ca','Canada'),
	('cv','Cape Verde'),
	('ky','Cayman Islands'),
	('cf','Central African Republic'),
	('td','Chad'),
	('cl','Chile'),
	('cn','China'),
	('cx','Christmas Island'),
	('cc','Cocos Islands'),
	('co','Colombia'),
	('km','Comoros'),
	('cg','Congo'),
	('cd','The Democratic Republic of The Congo'),
	('ck','Cook Islands'),
	('cr','Costa Rica'),
	('ci','Côte d''Ivoire'),
	('hr','Croatia'),
	('cu','Cuba'),
	('cw','Curaçao'),
	('cy','Cyprus'),
	('cz','Czech Republic'),
	('dk','Denmark'),
	('dj','Djibouti'),
	('dm','Dominica'),
	('do','Dominican Republic'),
	('ec','Ecuador'),
	('eg','Egypt'),
	('sv','El Salvador'),
	('gq','Equatorial Guinea'),
	('er','Eritrea'),
	('ee','Estonia'),
	('et','Ethiopia'),
	('fk','Falkland Islands'), 
	('fo','Faroe Islands'),
	('fj','Fiji'),
	('fi','Finland'),
	('fr','France'),
	('gf','French Guiana'),
	('pf','French Polynesia'),
	('tf','French Southern Territories'),
	('ga','Gabon'),
	('gm','Gambia'),
	('ge','Georgia'),
	('de','Germany'),
	('gh','Ghana'),
	('gi','Gibraltar'),
	('gr','Greece'),
	('gl','Greenland'),
	('gd','Grenada'),
	('gp','Guadeloupe'),
	('gu','Guam'),
	('gt','Guatemala'),
	('gg','Guernsey'),
	('gn','Guinea'),
	('gw','Guinea-bissau'),
	('gy','Guyana'),
	('ht','Haiti'),
	('hm','Heard and McDonald Islands'),
	('va','Holy See'),
	('hn','Honduras'),
	('hk','Hong Kong'),
	('hu','Hungary'),
	('is','Iceland'),
	('in','India'),
	('id','Indonesia'),
	('ir','Iran'),
	('iq','Iraq'),
	('ie','Ireland'),
	('im','Isle of Man'),
	('il','Israel'),
	('it','Italy'),
	('jm','Jamaica'),
	('jp','Japan'),
	('je','Jersey'),
	('jo','Jordan'),
	('kz','Kazakhstan'),
	('ke','Kenya'),
	('ki','Kiribati'),
	('kp','Democratic People''s Republic of Korea'),
	('kr','Republic of Korea'),
	('kw','Kuwait'),
	('kg','Kyrgyzstan'),
	('la','Lao People''s Democratic Republic'),
	('lv','Latvia'),
	('lb','Lebanon'),
	('ls','Lesotho'),
	('lr','Liberia'),
	('ly','Libya'),
	('li','Liechtenstein'),
	('lt','Lithuania'),
	('lu','Luxembourg'),
	('mo','Macao'),
	('mk','The Former Yugoslav Republic of Macedonia'),
	('mg','Madagascar'),
	('mw','Malawi'),
	('my','Malaysia'),
	('mv','Maldives'),
	('ml','Mali'),
	('mt','Malta'),
	('mh','Marshall Islands'),
	('mq','Martinique'),
	('mr','Mauritania'),
	('mu','Mauritius'),
	('yt','Mayotte'),
	('mx','Mexico'),
	('fm','Federated States of Micronesia'),
	('md','Republic of Moldova'),
	('mc','Monaco'),
	('mn','Mongolia'),
	('me','Montenegro'),
	('ms','Montserrat'),
	('ma','Morocco'),
	('mz','Mozambique'),
	('mm','Myanmar'),
	('na','Namibia'),
	('nr','Nauru'),
	('np','Nepal'),
	('nl','Netherlands'),
	('nc','New Caledonia'),
	('nz','New Zealand'),
	('ni','Nicaragua'),
	('ne','Niger'),
	('ng','Nigeria'),
	('nu','Niue'),
	('nf','Norfolk Island'),
	('mp','Northern Mariana Islands'),
	('no','Norway'),
	('om','Oman'),
	('pk','Pakistan'),
	('pw','Palau'),
	('ps','State of Palestine'),
	('pa','Panama'),
	('pg','Papua New Guinea'),
	('py','Paraguay'),
	('pe','Peru'),
	('ph','Philippines'),
	('pn','Pitcairn'),
	('pl','Poland'),
	('pt','Portugal'),
	('pr','Puerto Rico'),
	('qa','Qatar'),
	('re','Réunion'),
	('ro','Romania'),
	('ru','Russian Federation'),
	('rw','Rwanda'),
	('sh','Ascension and Tristan Da Cunha Saint Helena'),
	('bl','Saint Barthélemy'),
	('kn','Saint Kitts and Nevis'),
	('lc','Saint Lucia'),
	('pm','Saint Pierre and Miquelon'),
	('vc','Saint Vincent and The Grenadines'),
	('ws','Samoa'),
	('sm','San Marino'),
	('st','Sao Tome and Principe'),
	('sa','Saudi Arabia'),
	('sn','Senegal'),
	('rs','Serbia'),
	('sc','Seychelles'),
	('sl','Sierra Leone'),
	('sg','Singapore'),
	('sx','Sint Maarten'), 
	('sk','Slovakia'),
	('si','Slovenia'),
	('sb','Solomon Islands'),
	('so','Somalia'),
	('za','South Africa'),
	('gs','South Georgia and The South Sandwich Islands'),
	('ss','South Sudan'),
	('es','Spain'),
	('lk','Sri Lanka'),
	('sd','Sudan'),
	('sr','Suriname'),
	('sj','Svalbard and Jan Mayen Islands'),
	('sz','Swaziland'),
	('se','Sweden'),
	('ch','Switzerland'),
	('sy','Syrian Arab Republic'),
	('tw','Province of China Taiwan'),
	('tj','Tajikistan'),
	('tz','United Republic of Tanzania'),
	('th','Thailand'),
	('tl','Timor-leste'),
	('tg','Togo'),
	('tk','Tokelau'),
	('to','Tonga'),
	('tt','Trinidad and Tobago'),
	('tn','Tunisia'),
	('tr','Turkey'),
	('tm','Turkmenistan'),
	('tc','Turks and Caicos Islands'),
	('tv','Tuvalu'),
	('ug','Uganda'),
	('ua','Ukraine'),
	('ae','United Arab Emirates'),
	('gb','United Kingdom'),
	('us','United States'),
	('um','United States Minor Outlying Islands'),
	('uy','Uruguay'),
	('uz','Uzbekistan'),
	('vu','Vanuatu'),
	('ve','Bolivarian Republic of Venezuela'),
	('vn','Vietnam'),
	('vg','Virgin Islands (British)'),
	('vi','Virgin Islands (US)'),
	('wf','Wallis and Futuna Islands'),
	('eh','Western Sahara'),
	('ye','Yemen'),
	('zm','Zambia'),
	('zw','Zimbabwe');